# Generated by Django 3.0.5 on 2020-10-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edgarapp', '0004_directors'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingTOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('filing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_of_contents', to='edgarapp.Filing')),
            ],
        ),
    ]
